don't copy server-admin key unless requested

diff --git a/keygen b/keygen
--- a/keygen
+++ b/keygen
@@ -2,61 +2,114 @@
 
 set -e
 
-dir1=remote-keys
-dir2=local-keys
-comment1="admin key - copy public/private pair to remote host and public key to repository provider, eg. github"
+dir1=keys/server-admin-keys
+dir2=keys/deployer-keys
+reply1=""
+reply2=""
+reply3=""
+comment1="server admin key - copy public/private pair to remote host and public key to repository provider, eg. github"
 comment2="deployer key - copy public/private pair to local .ssh directory and public key to remote authorized_keys file"
-pass1=
-pass2=
-provider="codebasehq.com"
+pass1=""
+pass2=""
 
 for d in $dir1 $dir2; do
     if [ -e $d ]; then
         rm -rf $d
     fi
-    mkdir $d
+    mkdir -p $d
 done
 
 if [ -e .passphrase ]; then
     pass1=$(tr -d '\n' < .passphrase)
 else
-    echo -n "Passphrase: "
+    echo -n "Passphrase for new keys: "
 
     stty -echo
     read pass1
     stty echo
     echo ""
 
-    echo -n "Passphrase (again): "
+    if [ "$pass1" != "" ]; then
+        echo -n "Passphrase (again): "
 
-    stty -echo
-    read pass2
-    stty echo
-    echo ""
+        stty -echo
+        read pass2
+        stty echo
+        echo ""
 
-    if [ "$pass1" != "$pass2" ];then
-        echo "ERROR: passphrases didn't match"
-        exit 1
+        if [ "$pass1" != "$pass2" ];then
+            echo "ERROR: passphrases didn't match"
+            exit 1
+        fi
     fi
 fi
 
-ssh-keygen -q -C "$comment1" -f $dir1/admin.key -P "$pass1"
-ssh-keygen -q -C "$comment2" -f $dir2/deployer.key -P ""
-
-cp $dir2/deployer.key.pub $dir1/authorized_keys
-
-echo "" > $dir1/config
-echo "Host $provider" >> $dir1/config
-echo "IdentityFile ~/.ssh/admin.key" >> $dir1/config
-echo "" >> $dir1/config
-
-for d in $dir1 $dir2; do
-    if [ -e $d.zip ]; then
-        mv $d.zip $d.old.zip
+adminkey="$HOME/.ssh/server-admin.key"
+if [ -e $adminkey ] && [ -e $adminkey.pub ]; then
+    until [ "$reply1" = "y" ] || [ "$reply1" = "n" ]; do
+        echo -n "Use existing key '$adminkey'? (y/n) "
+        read reply1
+    done
+    if [ "$reply1" = "y" ]; then
+        cp $adminkey $dir1
+        cp $adminkey.pub $dir1
     fi
-    zip -r -0 -e -P "$pass1" -q $d.zip $d
-done
+fi
 
+if [ ! -e $dir1/server-admin.key ]; then
+    ssh-keygen -q -C "$comment1" -f $dir1/server-admin.key -P "$pass1"
+fi
+
+deployerkey="$HOME/.ssh/deployer.key"
+if [ -e $deployerkey ] && [ -e $deployerkey.pub ]; then
+    until [ "$reply2" = "y" ] || [ "$reply2" = "n" ]; do
+        echo -n "Use existing key '$deployerkey'? (y/n) "
+        read reply2
+    done
+    if [ "$reply2" = "y" ]; then
+        cp $deployerkey $dir2
+        cp $deployerkey.pub $dir2
+    fi
+fi
+
+if [ ! -e $dir2/deployer.key ]; then
+    ssh-keygen -q -C "$comment2" -f $dir2/deployer.key -P "$pass1"
+fi
+
+cp $dir2/deployer.key.pub tools/authorized_keys
+
+set +e
+sync=0
+for user in server-admin deployer; do
+    # cmp returns 1 for 'files are different', 2 for 'problem', otherwise 0
+    cmp $HOME/.ssh/$user.key keys/$user-keys/$user.key > /dev/null 2>&1
+    sync=$? || $sync
+    cmp $HOME/.ssh/$user.key.pub keys/$user-keys/$user.key.pub > /dev/null 2>&1
+    sync=$? || $sync
+done
+set -e
+
+if [ $sync -gt 0 ]; then
+    until [ "$reply3" = "y" ] || [ "$reply3" = "n" ]; do
+        echo -n "Copy new keys to local '$HOME/.ssh', overwriting if necessary? (y/n) "
+        read reply3
+    done
+    if [ "$reply3" = "y" ]; then
+        for user in server-admin deployer; do
+            cp keys/$user-keys/$user.key $HOME/.ssh/$user.key
+            cp keys/$user-keys/$user.key.pub $HOME/.ssh/$user.key.pub
+        done
+    fi
+fi
+
+cd keys
+for user in server-admin deployer; do
+    if [ -e $user-keys.zip ]; then
+        mv $user-keys.zip $user-keys.old.zip
+    fi
+    zip -r -0 -e -P "$pass1" -q $user-keys.zip $user-keys
+done
+cd ..
 rm -rf $dir1
 rm -rf $dir2
 
